PPAI-IVR/Models/DatosLlamadaViewModel.cs
using PPAI_IVR.Clases;

namespace PPAI_IVR.Models
{
    public class DatosLlamadaViewModel 
    {
        public string nombreCliente {  get; set; }

        public DescripcionCategoriaViewModel CategoriaAMostrar { get; set; }

        public List<string> audioMensajesValidaciones { get; set; }
        
    }
}

PPAI-IVR/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using PPAI_IVR.Migrations;
using PPAI_IVR.Models.Clases;
using PPAI_IVR.Servicios;

namespace PPAI_IVR.Controllers
{
    public class ClientesController : Controller
    {
        private readonly IRepositorioClientes repositorioClientes;

        public ClientesController(IRepositorioClientes repositorioClientes)
        {
            this.repositorioClientes = repositorioClientes;
        }

        public async Task<IActionResult> Index()
        {
            var clientes = await repositorioClientes.Obtener();
            return View(clientes);
        }

        public IActionResult Crear()
        {

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Crear(Cliente cliente)
        {
            if (!ModelState.IsValid)
            {

                return View(cliente);
            }


            cliente.InformacionDelCliente = null;
            var yaExisteCliente = await repositorioClientes.Existe(cliente.NombreCompleto, cliente.Dni);

            if (yaExisteCliente)
            {
                ModelState.AddModelError(nameof(cliente.NombreCompleto),
                    $"El nombre {cliente.NombreCompleto} Con el DNI {cliente.Dni} ya existe.");
                return View(cliente);
            }

            await repositorioClientes.Crear(cliente);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {

            var tipoCuenta = await repositorioClientes.ObtenerPorId(id);

            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            return View(tipoCuenta);
        }
        [HttpPost]
        public async Task<IActionResult> Editar(Cliente cliente)
        {

            var clienteee = await repositorioClientes.ObtenerPorId(cliente.Id);

            if (clienteee is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }


            await repositorioClientes.Actualizar(cliente);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Borrar(int id)
        {

            var cliente = await repositorioClientes.ObtenerPorId(id);

            if (cliente is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(cliente);

        }
        [HttpPost]
        public async Task<IActionResult> BorrarCliente(int id)
        {
            var cliente = await repositorioClientes.ObtenerPorId(id);

            if (cliente is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            await repositorioClientes.Borrar(id);
            return RedirectToAction("Index");
        }
    }
}

PPAI-IVR/Controllers/LlamadasController.cs
using Microsoft.AspNetCore.Mvc;
using PPAI_IVR.Clases;
using PPAI_IVR.Models.Clases;
using PPAI_IVR.Models;

namespace PPAI_IVR.Controllers
{
    public class LlamadasController : Controller
    {

        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> RegistrarLlamada()
        {
            return View();
        } 
        public async Task<IActionResult> LlamadaCU28()
        {
            return View();
        }


        public async Task<IActionResult> ComunicarseConOperador()
        {
            return View();
        }

        //public async Task<IActionResult> MostrarDatosLlamadaActual()
        //{
            
        //    GestorRegRespuestaOperador gestor = new GestorRegRespuestaOperador
        //    {
        //        LlamadaEnCurso = new Llamada
        //        {
        //            Cliente = new Cliente
        //            {
        //                Id = 1,
        //                NombreCompleto = "Antonio Lopez",
        //                InformacionDelCliente = new InformacionCliente
        //                {
                            
        //                        datoAValidar = "4 Hijos",
        //                        Id = 2,
                            
        //                }                  
                        
        //            },
        //            OpcionLlamada = new OpcionLlamada
        //            {

        //                validacionesRequeridas = new List<Validacion>
        //                {
        //                    new Validacion
        //                    {
        //                        Id = 1,
        //                        NroOrden = 1,
        //                        audioMensajeValidacion = " 2 Hijos",
        //                        Nombre = "Primera Opcion"
        //                    },
        //                    new Validacion
        //                    {
        //                        NroOrden= 2,
        //                        Id = 2,
        //                        audioMensajeValidacion = " 5 Hijos",
        //                        Nombre = "Segunda Opcion"
        //                    },
        //                    new Validacion
        //                    {
        //                        NroOrden = 3,
        //                        Id = 3,
        //                        audioMensajeValidacion = " 4 Hijos",
        //                        Nombre = "Tercera Opcion"
        //                    }
        //                },
        //                subOpcionesLlamada = new List<SubOpcionLlamada>{
        //    new SubOpcionLlamada{
        //        Id = 1,
        //        nombre = "Comunicarse con un Operador",
        //        nroOrden = 2
        //                        }
        //                                                            }
        //            }
        //        },
        //        CategoriaSeleccionada = new CategoriaLlamada
        //        {
        //            Id = 1,
        //            nombre = "Robo",
        //            nroOrden = 5,
        //            OpcionLlamada = new OpcionLlamada
        //            {
        //                Nombre = "Solicitar cancelación de la tarjeta de crédito"
        //            }
        //        }
        //    };

        //    DatosLlamadaViewModel paraMostrar = gestor.buscarDatosLlamadaActual();
        //    return View(paraMostrar);
        //}

        

    }
}

PPAI-IVR/Views/Shared/_DatosLlamada.cshtml
@using Microsoft.JSInterop;

@model GestorRegRespuestaOperador;
@{
    DatosLlamadaViewModel Datos = Model.buscarDatosLlamadaActual();

}

<div class="container">
    <div class="header col-12">
        <div>
            <a class="title">
                Nombre Cliente: @Datos.nombreCliente.ToString()
            </a>
        </div>
    </div>
    
    <dl class="post-info col-11">
        <div class="cr">
<<<<<<< HEAD
            <dt class="dt" ><b> Categoria Llamada: </b> @Model.CategoriaAMostrar.nombreCategoria.ToString()</dt>
            <dt class="dt" ><b> Opcion Seleccionada: </b> @Model.CategoriaAMostrar.OpcionLlamada.Nombre.ToString()</dt>
            <dt class="dt" ><b> Sub-Opcion Seleccionada: </b> @Model.CategoriaAMostrar.OpcionLlamada.subOpcionesLlamada[0].nombre.ToString()</dt>

            <dt class="dt">
                <b> Validaciones: </b>
                <select id="miSelect" onchange="habilitarTextarea()">
                    <option value="">Selecciona la validacion</option>
                    @foreach (string opcion in Model.Validaciones)
                    {
                        <option value="@opcion">@opcion</option>
                    }
                </select>
            </dt>

            <dt class="dt">
                <div class="mt-3">
                    <p class="col-8" style="align-content:center;"> <b> Descripcion de respuesta: </b></p><textarea id="miTextarea" disabled></textarea>
                </div>
            </dt>
        </div>
    </dl
=======
            <dt class="dt"> <b>Categoria Llamada: </b>  @Datos.CategoriaAMostrar.nombreCategoria.ToString()</dt>
            <dt class="dt"><b> Opcion Seleccionada: </b> @Datos.CategoriaAMostrar.OpcionLlamada.Nombre.ToString()</dt>
            <dt class="dt"><b> Sub-Opcion Seleccionada: </b> @Datos.CategoriaAMostrar.OpcionLlamada.subOpcionesLlamada[0].nombre.ToString()</dt>
            
        </div>
    </dl>
>>>>>>> 4db40c1b60bef897b85fd30733329f8248215693
</div>

@section Scripts{

}

PPAI-IVR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PPAI_IVR</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/PPAI_IVR.styles.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="~/css/operadorLlamada.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PPAI_IVR</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Llamadas" asp-action="RegistrarLlamada">RegistrarLLamada</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Llamadas" asp-action="ComunicarseConOperador">Comunicarse Con Operador</a>
                        </li>
                    </ul>
                    <partial name="_LinksLogin" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PPAI_IVR - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.5.0/knockout-min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PPAI-IVR/Views/Shared/_LinksLogin.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <span class="nav-link text-dark">Hola, @User.Identity.Name</span>
        </li>
        <li class="nav-item">
            <form class="form-inline" asp-action="logout" asp-controller="usuarios">
                <button type="submit" class="nav-link btn btn-link text-dark">
                    Logout
                </button>
            </form>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="usuarios" asp-action="Registro">
                Registro
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="usuarios" asp-action="Login">
                Login
            </a>
        </li>
    }
</ul>